# Generated by Django 4.1 on 2024-05-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceAgency_app', '0002_alter_slider_options_slider_my_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['my_order'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
